## 데이터 측정 기간 : 2016 ~ 2018
## 데이터 비교 데이터 : 없음



1. 현재 해당 서비스를 사용하고 있는 고객은 얼마나 있는가?
- 96096명

2. 고객은 주로 어디에서 거주하고 있는가?
- sao paulo / rio de janeiro / belo horizonte
  
3. 고객은 주로 어떤 결제 방법을 사용하고 있는가?
- credit_card

------------------------------------------------------------

4. 고객들의 평균 결제액?
- 

5. 일, 주, 월별 판매 트랜드
- 

6. 어떤 카테고리가 가장 많은 상품이 판매되었을까?
-

In [1]:
import pandas as pd

PATH = "00_data"

In [2]:
products = pd.read_csv(f"{PATH}/olist_products_dataset.csv", encoding="utf-8-sig")
customers = pd.read_csv(f"{PATH}/olist_customers_dataset.csv", encoding="utf-8-sig")
geolocation = pd.read_csv(f"{PATH}/olist_geolocation_dataset.csv", encoding="utf-8-sig")
order_items = pd.read_csv(f"{PATH}/olist_order_items_dataset.csv", encoding="utf-8-sig") 
payments = pd.read_csv(f"{PATH}/olist_order_payments_dataset.csv", encoding="utf-8-sig") 
reviews = pd.read_csv(f"{PATH}/olist_order_reviews_dataset.csv", encoding="utf-8-sig") 
orders = pd.read_csv(f"{PATH}/olist_orders_dataset.csv", encoding="utf-8-sig") 
sellers = pd.read_csv(f"{PATH}/olist_sellers_dataset.csv", encoding="utf-8-sig") 
category_name = pd.read_csv(f"{PATH}/product_category_name_translation.csv", encoding="utf-8-sig")

In [4]:
payments.head() # payment_value 쿠폰같은거 적용한 금액

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [5]:
order_items.head() # price, freight_value 순수한 상품가격과 배송비

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
orders.shape

(99441, 8)

In [9]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [10]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [11]:
orders = orders.dropna()

In [12]:
orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [13]:
orders.info() # 99441 -> 96461 결측치 제거 후 값이 변함

<class 'pandas.core.frame.DataFrame'>
Index: 96461 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96461 non-null  object
 1   customer_id                    96461 non-null  object
 2   order_status                   96461 non-null  object
 3   order_purchase_timestamp       96461 non-null  object
 4   order_approved_at              96461 non-null  object
 5   order_delivered_carrier_date   96461 non-null  object
 6   order_delivered_customer_date  96461 non-null  object
 7   order_estimated_delivery_date  96461 non-null  object
dtypes: object(8)
memory usage: 6.6+ MB

In [14]:
payments.shape

(103886, 5)

In [15]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [16]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

# 서로 다른 데이터프레임을 병합하고자 할 때 순서

1. 각 데이터프레임 내 결측치 값이 존재를 확인하고 제거한다
2. 데이터프레임을 연결할 수 있는 FK기 확인 -> order_id
3. FK가 각 데이터프레임 내 중복값을 가지고 있는지, 고유한 값이지 확인 -> 고유값이라고 확인 되면 그 때 병합

In [18]:
orders["order_id"].value_counts().max()

1

In [19]:
payments["order_id"].value_counts() # 중복사용되었음을 확인

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
fedcd9f7ccdc8cba3a18defedd1a5547    19
                                    ..
4b186efcda6f283e9c4a71332f6d3ad0     1
c11717d999ffc510a6441df946f0a94d     1
f593228a7a25e9633ff78a4ce0d0d4cc     1
387c2c33e495538e94878a500bf8e6d5     1
d5639d8a973cec351be75a3186835068     1
Name: count, Length: 99440, dtype: int64

In [20]:
payments = payments.groupby("order_id").sum()

In [25]:
payments = payments.reset_index()

In [26]:
payments["order_id"].value_counts().max()

1

In [27]:
payments.shape

(99440, 5)

In [29]:
import pandas as pd

merged_order = pd.merge(orders, payments, on="order_id", how="left")

In [30]:
merged_order.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,6.0,credit_cardvouchervoucher,3.0,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,boleto,1.0,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,credit_card,3.0,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,credit_card,1.0,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,credit_card,1.0,28.62

In [31]:
merged_order.shape

(96461, 12)

In [32]:
merged_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96461 entries, 0 to 96460
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96461 non-null  object
 1   customer_id                    96461 non-null  object
 2   order_status                   96461 non-null  object
 3   order_purchase_timestamp       96461 non-null  object
 4   order_approved_at              96461 non-null  object
 5   order_delivered_carrier_date   96461 non-null  object
 6   order_delivered_customer_date  96461 non-null  object
 7   order_estimated_delivery_date  96461 non-null  object
 8   payment_sequential             96460 non-null  float64
 9   payment_type                   96460 non-null  object
 10  payment_installments           96460 non-null  float64
 11  payment_value                  96460 non-null  float64
dtypes: float64(3), object(9)
memory usage: 8.8+ MB

In [33]:
merged_order = merged_order.dropna()

In [34]:
merged_order.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96460 entries, 0 to 96460
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96460 non-null  object
 1   customer_id                    96460 non-null  object
 2   order_status                   96460 non-null  object
 3   order_purchase_timestamp       96460 non-null  object
 4   order_approved_at              96460 non-null  object
 5   order_delivered_carrier_date   96460 non-null  object
 6   order_delivered_customer_date  96460 non-null  object
 7   order_estimated_delivery_date  96460 non-null  object
 8   payment_sequential             96460 non-null  float64
 9   payment_type                   96460 non-null  object
 10  payment_installments           96460 non-null  float64
 11  payment_value                  96460 non-null  float64
dtypes: float64(3), object(9)
memory usage: 9.6+ MB

In [35]:
merged_order.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
dtype: int64

In [37]:
merged_order.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,6.0,credit_cardvouchervoucher,3.0,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,boleto,1.0,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,credit_card,3.0,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,credit_card,1.0,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,credit_card,1.0,28.62

In [38]:
merged_order.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96460 entries, 0 to 96460
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96460 non-null  object
 1   customer_id                    96460 non-null  object
 2   order_status                   96460 non-null  object
 3   order_purchase_timestamp       96460 non-null  object
 4   order_approved_at              96460 non-null  object
 5   order_delivered_carrier_date   96460 non-null  object
 6   order_delivered_customer_date  96460 non-null  object
 7   order_estimated_delivery_date  96460 non-null  object
 8   payment_sequential             96460 non-null  float64
 9   payment_type                   96460 non-null  object
 10  payment_installments           96460 non-null  float64
 11  payment_value                  96460 non-null  float64
dtypes: float64(3), object(9)
memory usage: 9.6+ MB

In [40]:
# 날짜에 따른 결제금약을 시계열차트로 정렬해서 시각화를 하려고 하는데
# 그러려면 해당 데이터의 타입이 문자가 아니라 날짜 타입이 되어야한다
# 현재 오브젝트(문자)이기 때문에 날짜 타입으로 변경하고자 함

import pandas as pd

df = pd.DataFrame({
    "order": [
        "2020-01-01 01:10:00",
        "2020-01-08 07:20:00",
        "2020-02-20 11:20:00",
        "2020-02-20 04:40:00",
        "2020-02-28 12:10:20",
        "2020-01-10 17:23:50",
        "2020-06-20 22:27:50",
        "2020-06-20 21:15:59",
        "2020-12-10 21:27:59"
    ]
})

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   order   9 non-null      object
dtypes: object(1)
memory usage: 204.0+ bytes

In [45]:
import pandas as pd

df["order"] = pd.to_datetime(df["order"], format="%Y-%m-%d %H:%M:%S", errors="raise")

### to_datetime() -> 날짜 옵션목록

1. %y : 연도를 두 글자로 표기
2. %Y : 연도를 네 글자로 표기
3. %m : 월을 두 글자로 표기 (01~12)
4. %d : 일을 두 글자로 표기 (01~31)
5. %H : 시간을 24시간 기준 표기 (00~23)
6. %M : 분을 두 글자로 표기 (00~59)
7. %S : 초를 두 글자로 표기 (00~59)


- errors : 만약 날짜형태로 값을 바꾸기에 불출족한 조건 문자열
- errors=ignore : 무시하고 진행
- errors=raise : 에러를 표기하고 어떤 에러인지 표기
- errors=coerce : 에러를 NaT 형태로 값을 변환하고 진행

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   order   9 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 204.0 bytes