In [1]:
import pandas as pd

# 데이터프레임을 만드는 방법.여러 시리즈가 있기 때문에 필드명을 써줘야한다
df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],     
    "한국": [0.4, 0.5, 0.45],     
    "중국": [10, 13, 15]     
})

# 지금까지 파이썬에서는 {} 딕셔러니, [] 리스트라고 했지만, pnadas에서는 다르다

In [2]:
df

    미국    한국  중국
0  2.1  0.40  10
1  2.2  0.50  13
2  2.3  0.45  15

In [3]:
# 인덱스 값을 설정하는 방법
# 인덱스 명이 변경된 것처럼 보이지만, 인덱스의 오리지널은 결국 0부터 시작해서 1씩 증가하는 속성을 가지고 있다

df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],     
    "한국": [0.4, 0.5, 0.45],     
    "중국": [10, 13, 15],
},index=[2000, 2010, 2020])

In [4]:
df

       미국    한국  중국
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [5]:
# 데이터프레임안에 인덱스를 조회하는 방법

df.index

Index([2000, 2010, 2020], dtype='int64')

In [6]:
# 인덱스의 값을 수정하는 방법

df.index = [2001, 2002, 2003]

In [7]:
df

       미국    한국  중국
2001  2.1  0.40  10
2002  2.2  0.50  13
2003  2.3  0.45  15

In [11]:
df.columns

Index(['일본', '필리핀', '러시아'], dtype='object')

In [9]:
# 필드명을 바꾸는 방법

df.columns = ["일본", "필리핀", "러시아"]

In [10]:
df

       일본   필리핀  러시아
2001  2.1  0.40   10
2002  2.2  0.50   13
2003  2.3  0.45   15

In [12]:
df.values

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [13]:
df = pd.DataFrame({
    "년도" : [2000, 2110, 2020],
    "미국": [2.1, 2.2, 2.3],     
    "한국": [0.4, 0.5, 0.45],     
    "중국": [10, 13, 15]
})

In [14]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2110  2.2  0.50  13
2  2020  2.3  0.45  15

In [15]:
# 시리즈를 인덱스로 바꿔서 보는 방법 (임시적)

df.set_index("년도")

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [17]:
# 시리즈를 인덱스로 바꾸는 방법

df = df.set_index("년도")

In [18]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [ ]:
# 인덱스를 시리즈로 바꿔서 보는 방법 (임시적)

df.reset_index("년도")

In [19]:
# 인덱스를 시리즈로 바꾸는 방법

df = df.reset_index("년도")

In [20]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2110  2.2  0.50  13
2  2020  2.3  0.45  15

In [21]:
df = df.set_index("년도")

In [22]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [26]:
df.index.name = "연도"

In [27]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [28]:
df = df.reset_index("연도")

In [29]:
df

     연도   미국    한국  중국
0  2000  2.1  0.40  10
1  2110  2.2  0.50  13
2  2020  2.3  0.45  15

In [30]:
df = df.set_index("연도")
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [31]:
df.loc[2000]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [33]:
df.iloc[0]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [34]:
type(df.loc[2000])

pandas.core.series.Series

In [35]:
df["미국"]

연도
2000    2.1
2110    2.2
2020    2.3
Name: 미국, dtype: float64

In [36]:
type(df["미국"])

pandas.core.series.Series

In [43]:
print(df["미국"][2000]) # 열 방식
print(df.loc[2000]["미국"]) # 행 방식
print(df.iloc[0]["미국"]) # 행 방식2

2.1
2.1
2.1

In [44]:
df = pd.DataFrame({
    "년도" : ["2000", "2110", "2020"],
    "미국": [2.1, 2.2, 2.3],     
    "한국": [0.4, 0.5, 0.45],     
    "중국": [10, 13, 15]
})

df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2110  2.2  0.50  13
2  2020  2.3  0.45  15

In [45]:
df = df.set_index("년도")
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [47]:
df.loc["2000"]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [48]:
df.index

Index(['2000', '2110', '2020'], dtype='object', name='년도')

In [49]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [50]:
df .columns

Index(['미국', '한국', '중국'], dtype='object')

In [51]:
# 새로운 시리즈를 추가하는 방식

df["일본"] = [1, 2, 3]

In [52]:
df

       미국    한국  중국  일본
년도
2000  2.1  0.40  10   1
2110  2.2  0.50  13   2
2020  2.3  0.45  15   3

In [53]:
del df["일본"]

In [54]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [55]:
df.loc["2021"] = [1, 2, 3]

In [56]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15
2021  1.0  2.00   3

In [57]:
# 인덱스를 기반으로 한 행을 삭제해서 보는 방법

df.drop(["2021"])

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [58]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15
2021  1.0  2.00   3

In [59]:
df = df.drop(["2021"])

In [60]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2110  2.2  0.50  13
2020  2.3  0.45  15

In [ ]:
df = df.reset_index("년도")

In [64]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2110  2.2  0.50  13
2  2020  2.3  0.45  15

In [65]:
# 로우데이터를 건드리지 않고 원하는 시리즈만 모아서 볼 수 있는 방법

df2 = df[["한국", "중국"]].copy()

In [66]:
df2

     한국  중국
0  0.40  10
1  0.50  13
2  0.45  15

In [67]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2110  2.2  0.50  13
2  2020  2.3  0.45  15

In [68]:
df2.columns

Index(['한국', '중국'], dtype='object')

In [69]:
df2.columns = ["브라질", "아르헨티나"]

In [70]:
df2

    브라질  아르헨티나
0  0.40     10
1  0.50     13
2  0.45     15

In [71]:
df2["년도"] = [2000, 2010, 2020]

In [73]:
df2

    브라질  아르헨티나    년도
0  0.40     10  2000
1  0.50     13  2010
2  0.45     15  2020

In [74]:
df2 = df2.set_index("년도")

In [75]:
df2

       브라질  아르헨티나
년도
2000  0.40     10
2010  0.50     13
2020  0.45     15