In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "customer_id": [1, 2, 3],
    "customer_name": ["Robert", "Peter", "David"]
})

df1

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3         David

In [2]:
import pandas as pd

df2 = pd.DataFrame({
    "id" : [1, 2, 4],
    "order_id" : [100, 200, 300],
    "otder_date" : ["2021-01-21", "2021-02-03", "2020-10-01"]
})

df2

   id  order_id  otder_date
0   1       100  2021-01-21
1   2       200  2021-02-03
2   4       300  2020-10-01

In [3]:
# concat() : 서로 다른 두 개의 데이터 프레임을 물리적으로 합쳐주는 매서드 (디폴트는 상, 하의 위치로 합친디)

pd.concat([df1, df2])

   id  customer_id customer_name  order_id  otder_date
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0         David       NaN         NaN
0   1          NaN           NaN     100.0  2021-01-21
1   2          NaN           NaN     200.0  2021-02-03
2   4          NaN           NaN     300.0  2020-10-01

In [4]:
# 0 -> 상하의 위치, 1 -> 위, 아래의 위치

pd.concat([df1, df2], axis=1)

   id  customer_id customer_name  id  order_id  otder_date
0   1            1        Robert   1       100  2021-01-21
1   2            2         Peter   2       200  2021-02-03
2   3            3         David   4       300  2020-10-01

In [5]:
# merge() : 서로 다른 두 개의 데이터프레임 안에 동일한 이름을 가진 칼럼을 기준으로 합침

pd.merge(df1, df2) # 각 데이터프레임의 필드명을 왼쪽부터 조회 ->  상호동일한 필드명이 조회되면 그 것을 기준으로 합친다

   id  customer_id customer_name  order_id  otder_date
0   1            1        Robert       100  2021-01-21
1   2            2         Peter       200  2021-02-03

In [6]:
pd.merge(df1, df2, on="id")

   id  customer_id customer_name  order_id  otder_date
0   1            1        Robert       100  2021-01-21
1   2            2         Peter       200  2021-02-03

In [ ]:
# merge(데이터프레임1, 데이터프레임2, 연결필드, how=결합방법)
# inner : SQL 이너조인과 동일한 방법으로 연결
# outer : 각 데이터프레임의 인덱스값을 기준으로 서로 다른 데이터프레임을 연결하겠다는 의미
# left : SQL LEFT OUTER JOIN과 동일 (NULL값이 있기 떄문에 잘 사용하지 않는다)
# right : SQL RIGHT OUTER JOIN과 동일 (NULL값이 있기 떄문에 잘 사용하지 않는다)

In [7]:
import pandas as pd

pd.merge(df1, df2, on="id", how="inner") # 애초에 디폴트 값이 inner join

   id  customer_id customer_name  order_id  otder_date
0   1            1        Robert       100  2021-01-21
1   2            2         Peter       200  2021-02-03

In [8]:
import pandas as pd

pd.merge(df1, df2, on="id", how="outer")

   id  customer_id customer_name  order_id  otder_date
0   1          1.0        Robert     100.0  2021-01-21
1   2          2.0         Peter     200.0  2021-02-03
2   3          3.0         David       NaN         NaN
3   4          NaN           NaN     300.0  2020-10-01

In [9]:
import pandas as pd

pd.merge(df1, df2, on="id", how="left")

   id  customer_id customer_name  order_id  otder_date
0   1            1        Robert     100.0  2021-01-21
1   2            2         Peter     200.0  2021-02-03
2   3            3         David       NaN         NaN

In [10]:
import pandas as pd

pd.merge(df1, df2, on="id", how="right")

   id  customer_id customer_name  order_id  otder_date
0   1          1.0        Robert       100  2021-01-21
1   2          2.0         Peter       200  2021-02-03
2   4          NaN           NaN       300  2020-10-01

In [14]:
df1 = df1.set_index("id")

In [15]:
df1

    customer_id customer_name
id
1             1        Robert
2             2         Peter
3             3         David

In [16]:
df2 = df2.set_index("id")
df2

    order_id  otder_date
id
1        100  2021-01-21
2        200  2021-02-03
4        300  2020-10-01

In [17]:
pd.merge(df1, df2, left_index=True, right_index=True) # how=inner 가 생략되어있다

    customer_id customer_name  order_id  otder_date
id
1             1        Robert       100  2021-01-21
2             2         Peter       200  2021-02-03

In [18]:
pd.merge(df1, df2, how="outer", left_index=True, right_index=True)

    customer_id customer_name  order_id  otder_date
id
1           1.0        Robert     100.0  2021-01-21
2           2.0         Peter     200.0  2021-02-03
3           3.0         David       NaN         NaN
4           NaN           NaN     300.0  2020-10-01