In [1]:
# pandas 파일 로드

import pandas as pd

doc = pd.read_csv("00_data/olist_customers_dataset.csv", encoding="utf-8-sig")
doc.head()

                        customer_id  ... customer_state
0  06b8999e2fba1a1fbc88172c00ba8bc7  ...             SP
1  18955e83d337fd6b2def6b18a428ac77  ...             SP
2  4e7b3e00288586ebd08712fdd0374a03  ...             SP
3  b2b6027bc5c5109e529d4dc6358b12c3  ...             SP
4  4f2d8ab171c80ec8364f7c12e35b23ad  ...             SP

[5 rows x 5 columns]

In [3]:
# 데이터 사이즈

doc.shape

(99441, 5)

In [4]:
# 데이터 상세명세서 확인

doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [5]:
# 데이터 필드명 및 컬럼목록

doc.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [6]:
# 데이터 인덱스 (측정기준값)

doc.index

RangeIndex(start=0, stop=99441, step=1)

In [7]:
# 데이터 5 numbers summary

doc.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [8]:
# 데이터 상위 5개 확인하기

doc.head()

                        customer_id  ... customer_state
0  06b8999e2fba1a1fbc88172c00ba8bc7  ...             SP
1  18955e83d337fd6b2def6b18a428ac77  ...             SP
2  4e7b3e00288586ebd08712fdd0374a03  ...             SP
3  b2b6027bc5c5109e529d4dc6358b12c3  ...             SP
4  4f2d8ab171c80ec8364f7c12e35b23ad  ...             SP

[5 rows x 5 columns]

In [10]:
# 로우데이터에서 필요하다고 판판되는 컬럼만 별도로 추출해서 가져오기

doc2 = doc[["customer_zip_code_prefix", "customer_city", "customer_state"]].copy()
doc2

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 3 columns]

In [12]:
# 현재 카피해온 데이터프레임 안에서 특정 조건에 해당되는 값만 추출해오기

doc3 = doc2[doc2["customer_city"] == "sao paulo"]
doc3.shape

(15540, 3)

In [14]:
# 특정 데이터프레임 내, 컬럼을 기준으로 값의 갯수 확인

doc2["customer_city"].value_counts()

customer_city
sao paulo                   15540
rio de janeiro               6882
belo horizonte               2773
brasilia                     2131
curitiba                     1521
                            ...
olhos d'agua                    1
pacotuba                        1
sao sebastiao do paraiba        1
benedito leite                  1
campos verdes                   1
Name: count, Length: 4119, dtype: int64

In [15]:
# 특정 데이터프레임 내, 그룹화 (그룹화의 대상 = 인덱스)

doc4 = doc2.groupby("customer_city").count()
doc4

                     customer_zip_code_prefix  customer_state
customer_city
abadia dos dourados                         3               3
abadiania                                   1               1
abaete                                     12              12
abaetetuba                                 11              11
abaiara                                     2               2
...                                       ...             ...
xinguara                                    9               9
xique-xique                                 3               3
zacarias                                    2               2
ze doca                                     5               5
zortea                                      2               2

[4119 rows x 2 columns]

In [17]:
# 특정 데이터프레임 내 인덱스의 길이 확인

len(doc4.index)
doc4.shape

(4119, 2)

In [18]:
# 특정 데이터프레임 내 상위 5개 문서 조회

doc4.head()

                     customer_zip_code_prefix  customer_state
customer_city
abadia dos dourados                         3               3
abadiania                                   1               1
abaete                                     12              12
abaetetuba                                 11              11
abaiara                                     2               2

In [20]:
doc4 = doc.groupby("customer_city").count()
doc4

                     customer_id  ...  customer_state
customer_city                     ...
abadia dos dourados            3  ...               3
abadiania                      1  ...               1
abaete                        12  ...              12
abaetetuba                    11  ...              11
abaiara                        2  ...               2
...                          ...  ...             ...
xinguara                       9  ...               9
xique-xique                    3  ...               3
zacarias                       2  ...               2
ze doca                        5  ...               5
zortea                         2  ...               2

[4119 rows x 4 columns]

In [22]:
# 특정 데이터프레임 내 컬럼을 기준으로 정렬

# doc4["customer_id"].sort_values() # 기본적으로 오름차순 정렬
doc4["customer_id"].sort_values(ascending=False)

customer_city
sao paulo         15540
rio de janeiro     6882
belo horizonte     2773
brasilia           2131
curitiba           1521
                  ...
agisse                1
vieiras               1
bertopolis            1
abadiania             1
xexeu                 1
Name: customer_id, Length: 4119, dtype: int64

In [23]:
# N번째 데이터 조회

doc4["customer_id"].sort_values(ascending=False).head() #head()에 매개변수가 존재하지 않으면 기본적으로 top5만 찾아온다

customer_city
sao paulo         15540
rio de janeiro     6882
belo horizonte     2773
brasilia           2131
curitiba           1521
Name: customer_id, dtype: int64

In [24]:
doc4.head()

                     customer_id  ...  customer_state
customer_city                     ...
abadia dos dourados            3  ...               3
abadiania                      1  ...               1
abaete                        12  ...              12
abaetetuba                    11  ...              11
abaiara                        2  ...               2

[5 rows x 4 columns]

In [25]:
# 특정 데이터프레임 내 인덱스를 새롭게 정의

doc4.set_index("customer_id")

             customer_unique_id  customer_zip_code_prefix  customer_state
customer_id
3                             3                         3               3
1                             1                         1               1
12                           12                        12              12
11                           11                        11              11
2                             2                         2               2
...                         ...                       ...             ...
9                             9                         9               9
3                             3                         3               3
2                             2                         2               2
5                             5                         5               5
2                             2                         2               2

[4119 rows x 3 columns]

In [27]:
doc.set_index("customer_city")

                                            customer_id  ... customer_state
customer_city                                            ...
franca                 06b8999e2fba1a1fbc88172c00ba8bc7  ...             SP
sao bernardo do campo  18955e83d337fd6b2def6b18a428ac77  ...             SP
sao paulo              4e7b3e00288586ebd08712fdd0374a03  ...             SP
mogi das cruzes        b2b6027bc5c5109e529d4dc6358b12c3  ...             SP
campinas               4f2d8ab171c80ec8364f7c12e35b23ad  ...             SP
...                                                 ...  ...            ...
sao paulo              17ddf5dd5d51696bb3d7c6291687be6f  ...             SP
taboao da serra        e7b71a9017aa05c9a7fd292d714858e8  ...             SP
fortaleza              5e28dfe12db7fb50a4b2f691faecea5e  ...             CE
canoas                 56b18e2166679b8a959d72dd06da27f9  ...             RS
cotia                  274fa6071e5e17fe303b9748641082c8  ...             SP

[99441 rows x 4 columns]

In [28]:
# 데이터프레임 > 인덱스 내 정렬앷

doc.set_index("customer_city").sort_index()

                                          customer_id  ... customer_state
customer_city                                          ...
abadia dos dourados  a23e3f9a2b656b23b7e52075964b42cd  ...             MG
abadia dos dourados  9e01f714a2b3b8962c222cf2b74c20dc  ...             MG
abadia dos dourados  f11eb8f0b8b87510a93e3e1aa10b0ade  ...             MG
abadiania            576d71ddb21b21763cfedce73b902180  ...             GO
abaete               5e9e1ae42e02df93e9a591e86fd531a3  ...             MG
...                                               ...  ...            ...
ze doca              1052e334b46dd1e9876946d6372a363e  ...             MA
ze doca              d8b3ef6f73de33ae716e94d2478cc080  ...             MA
ze doca              fc87e5c06780700952aa42998a22968f  ...             MA
zortea               0a466d490a3c2fcc1e7177f4809ec7dd  ...             SC
zortea               e046f992a304cc92e1b00d7fccdf1c42  ...             SC

[99441 rows x 4 columns]

In [29]:
doc2

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 3 columns]

In [31]:
doc2["customer_state"].value_counts().shape

(27,)

In [33]:
# 특정 데이터프레임 안에서 인덱스 요소를 해제하고 원래 컬럼 자리로 이동

doc4 = doc4.reset_index()

In [34]:
doc4

            customer_city  ...  customer_state
0     abadia dos dourados  ...               3
1               abadiania  ...               1
2                  abaete  ...              12
3              abaetetuba  ...              11
4                 abaiara  ...               2
...                   ...  ...             ...
4114             xinguara  ...               9
4115          xique-xique  ...               3
4116             zacarias  ...               2
4117              ze doca  ...               5
4118               zortea  ...               2

[4119 rows x 5 columns]

In [37]:
doc4[doc4["customer_id"] > 1000].shape

(9, 5)

In [39]:
doc4 = doc4.set_index("customer_city")
doc4

                     customer_id  ...  customer_state
customer_city                     ...
abadia dos dourados            3  ...               3
abadiania                      1  ...               1
abaete                        12  ...              12
abaetetuba                    11  ...              11
abaiara                        2  ...               2
...                          ...  ...             ...
xinguara                       9  ...               9
xique-xique                    3  ...               3
zacarias                       2  ...               2
ze doca                        5  ...               5
zortea                         2  ...               2

[4119 rows x 4 columns]

In [40]:
doc4[doc4["customer_id"] > 1000].index

Index(['belo horizonte', 'brasilia', 'campinas', 'curitiba', 'guarulhos',
       'porto alegre', 'rio de janeiro', 'salvador', 'sao paulo'],
      dtype='object', name='customer_city')

In [41]:
doc4 = doc4.reset_index()
doc4

            customer_city  ...  customer_state
0     abadia dos dourados  ...               3
1               abadiania  ...               1
2                  abaete  ...              12
3              abaetetuba  ...              11
4                 abaiara  ...               2
...                   ...  ...             ...
4114             xinguara  ...               9
4115          xique-xique  ...               3
4116             zacarias  ...               2
4117              ze doca  ...               5
4118               zortea  ...               2

[4119 rows x 5 columns]

In [42]:
doc

                            customer_id  ... customer_state
0      06b8999e2fba1a1fbc88172c00ba8bc7  ...             SP
1      18955e83d337fd6b2def6b18a428ac77  ...             SP
2      4e7b3e00288586ebd08712fdd0374a03  ...             SP
3      b2b6027bc5c5109e529d4dc6358b12c3  ...             SP
4      4f2d8ab171c80ec8364f7c12e35b23ad  ...             SP
...                                 ...  ...            ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  ...             SP
99437  e7b71a9017aa05c9a7fd292d714858e8  ...             SP
99438  5e28dfe12db7fb50a4b2f691faecea5e  ...             CE
99439  56b18e2166679b8a959d72dd06da27f9  ...             RS
99440  274fa6071e5e17fe303b9748641082c8  ...             SP

[99441 rows x 5 columns]

In [44]:
# 특정 데이터프레임의 결측치 존재 여부 확인

# doc.isnull()
doc.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [47]:
# 수집된 데이터를 기반으로 리스트로 변경하기

#doc.drop_duplicates(subset="customer_city", keep="first") # first: 중복 값중 최초값만 살림 , last : 중복 값중 최종값만 살림
doc.drop_duplicates(subset="customer_city", keep="first")["customer_city"].to_list()

['franca',
 'sao bernardo do campo',
 'sao paulo',
 'mogi das cruzes',
 'campinas',
 'jaragua do sul',
 'timoteo',
 'curitiba',
 'belo horizonte',
 'montes claros',
 'rio de janeiro',
 'lencois paulista',
 'caxias do sul',
 'piracicaba',
 'guarulhos',
 'pacaja',
 'florianopolis',
 'aparecida de goiania',
 'santo andre',
 'goiania',
 'cachoeiro de itapemirim',
 'sao jose dos campos',
 'sao roque',
 'camacari',
 'resende',
 'sumare',
 'novo hamburgo',
 'sao luis',
 'sao jose',
 'santa barbara',
 'ribeirao preto',
 'ituiutaba',
 'taquarituba',
 'sao jose dos pinhais',
 'barrinha',
 'parati',
 'dourados',
 'trindade',
 'cascavel',
 'fortaleza',
 'brasilia',
 'pelotas',
 'porto alegre',
 'salto',
 'jundiai',
 'cacapava',
 'sao vicente',
 'uberlandia',
 'botelhos',
 'sao goncalo',
 'araucaria',
 'nova iguacu',
 'areia branca',
 'campos dos goytacazes',
 'sao carlos',
 'itajuba',
 'cruz das almas',
 'vassouras',
 'feira de santana',
 'niteroi',
 'sobral',
 'divinopolis',
 'paraiba do sul',
 'paulista',
 'carapicuiba',
 'bom principio',
 'astolfo dutra',
 'marialva',
 'sao jose do rio preto',
 'cabo frio',
 'contagem',
 'cafeara',
 'sao joaquim da barra',
 'foz do iguacu',
 'suzano',
 'timbo',
 'camboriu',
 'nova bassano',
 'rio grande',
 'braganca paulista',
 'barra do garcas',
 'embu',
 'urussanga',
 'silvianopolis',
 'gameleiras',
 'belem',
 'pocos de caldas',
 'santos',
 'piracaia',
 'sinop',
 'guaruja',
 'barueri',
 'feliz',
 'jambeiro',
 'ipatinga',
 'tupa',
 'blumenau',
 'moncoes',
 'balneario camboriu',
 'vargem grande',
 'rio brilhante',
 'eugenopolis',
 'paulinia',
 'apucarana',
 'recife',
 'osasco',
 'valinhos',
 'manaus',
 'cidreira',
 'santiago',
 'sao sepe',
 'alta floresta',
 'jaboatao dos guararapes',
 'ibatiba',
 'hortolandia',
 'cotia',
 'macae',
 'saudades',
 'macapa',
 'salto de pirapora',
 'taboao da serra',
 'bom jesus',
 'santa cruz do rio pardo',
 'diadema',
 'santa ines',
 'serrinha',
 'votorantim',
 'itatiaia',
 'duque de caxias',
 'varre-sai',
 'vila velha',
 'mangaratiba',
 'atibaia',
 'salvador',
 'maceio',
 'birigui',
 'petropolis',
 'sao pedro',
 'jaguariaiva',
 'franco da rocha',
 'pindamonhangaba',
 'irati',
 'ribeira',
 'barbacena',
 'limoeiro',
 'espigao do oeste',
 'belford roxo',
 'coronel fabriciano',
 'itanhaem',
 'bebedouro',
 'americana',
 'uba',
 'arapongas',
 'vinhedo',
 'itajai',
 'bauru',
 'pradopolis',
 'aripuana',
 'guaratinga',
 'ponta pora',
 'aracatuba',
 'volta redonda',
 'maringa',
 'araraquara',
 'matipo',
 'santo antonio da patrulha',
 'barra mansa',
 'diamantina',
 'mairinque',
 'capitao leonidas marques',
 'sao sebastiao do paraiso',
 'rosario do sul',
 'itaguai',
 'paraopeba',
 'guarapuava',
 'crisolita',
 'pirai',
 'linhares',
 'agudos',
 'sao joao de meriti',
 'navegantes',
 'pirassununga',
 'faxinal dos guedes',
 'criciuma',
 'nova venecia',
 'passo fundo',
 'ibia',
 'manhuacu',
 'altamira',
 'aperibe',
 'cuiaba',
 'canoas',
 'cubatao',
 'campo limpo paulista',
 'cambe',
 'itaquaquecetuba',
 'sao caetano do sul',
 'sao goncalo do rio abaixo',
 'rolandia',
 'tres coracoes',
 'cacapava do sul',
 'sao joao nepomuceno',
 'leme',
 'araras',
 'cortes',
 'brusque',
 'montenegro',
 'itaberai',
 'santa rosa de viterbo',
 'agua fria de goias',
 'marau',
 'curvelo',
 'juiz de fora',
 'mogi-guacu',
 'guaratingueta',
 'paranagua',
 'lins',
 'campo bom',
 'sertaozinho',
 'tres lagoas',
 'jau',
 'campos de julio',
 'saquarema',
 'artur nogueira',
 'uaua',
 'jandira',
 'concordia',
 'nova friburgo',
 'sorocaba',
 'ponte nova',
 'araquari',
 'muriae',
 'nova lima',
 'inhumas',
 'italva',
 'tres rios',
 'santa maria',
 'itagiba',
 'paracatu',
 'xaxim',
 'laranjeiras do sul',
 'itapiuna',
 'formosa',
 'ivoti',
 'juazeiro',
 'ponta grossa',
 'campina grande',
 'maua',
 'salgueiro',
 'lorena',
 'toledo',
 'sao pedro da aldeia',
 'vianopolis',
 'arapiraca',
 'porto seguro',
 'ariquemes',
 'presidente getulio',
 'rio negro',
 'ribeirao pires',
 'sao jose da coroa grande',
 'agua doce do norte',
 'anapolis',
 'guararapes',
 'farroupilha',
 'almenara',
 'rio das ostras',
 'gravatai',
 'brumado',
 'marilia',
 'itabira',
 'claudia',
 'para de minas',
 'miguelopolis',
 'terra roxa',
 'araguari',
 'lages',
 'embu das artes',
 'limeira',
 'taubate',
 'santa fe do sul',
 'caieiras',
 'carangola',
 'chapada do norte',
 'loanda',
 'passa tres',
 'aracoiaba da serra',
 'itaborai',
 'vitoria',
 'sao bento do sul',
 'indaiatuba',
 'boituva',
 'teresopolis',
 'pinhalzinho',
 'petrolina',
 'natal',
 'barreiras',
 'januaria',
 'ipiabas',
 'firminopolis',
 'joinville',
 'mococa',
 'valenca',
 'sao miguel do oeste',
 'jales',
 'rio formoso',
 'angra dos reis',
 'alfredo chaves',
 'itapetinga',
 'gurupi',
 'nucleo residencial pilar',
 'coromandel',
 'charqueada',
 'itau de minas',
 'ibiruba',
 'bertioga',
 'ipiau',
 'matozinhos',
 'teresina',
 'entre rios',
 'juina',
 'mairipora',
 'marechal candido rondon',
 'avare',
 'icem',
 'sao sebastiao',
 'serra',
 'mirassol',
 'taperuaba',
 'alfenas',
 'leopoldina',
 'sao joao da boa vista',
 'parnamirim',
 'teixeira de freitas',
 'joao pessoa',
 'chacara',
 'rio novo do sul',
 'guapore',
 'rio branco',
 'ferraz de vasconcelos',
 'petrolandia',
 'araruna',
 'gravata',
 'alegre',
 'londrina',
 'senhor do bonfim',
 'santana de parnaiba',
 'piratininga',
 'monte carmelo',
 'ipiranga',
 'jacarei',
 'picos',
 'una',
 'taguai',
 'peabiru',
 'conquista',
 'bicas',
 'forquilha',
 'guaicara',
 'santa vitoria',
 'adamantina',
 'rio claro',
 'sao jose de uba',
 'sorriso',
 'aracaju',
 'conselheiro lafaiete',
 'taguatinga',
 'tiangua',
 'paranaiba',
 'david canabarro',
 'itarare',
 'cajueiro',
 'cruzeiro',
 'santa cruz do sul',
 'presidente epitacio',
 'castanhal',
 'cariacica',
 'bom jesus dos perdoes',
 'urucurituba',
 'olinda',
 'sao jose do rio pardo',
 'guapimirim',
 'vargem grande paulista',
 'chapeco',
 'videira',
 'canapi',
 'pontal do parana',
 'bento goncalves',
 'caceres',
 'bituruna',
 'sao bento do sapucai',
 'mage',
 'forquilhinha',
 'itaberaba',
 'gramado',
 'guacui',
 'pato branco',
 'itanhem',
 'palmas',
 'bage',
 'francisco morato',
 'cosmopolis',
 'carmo',
 'armacao dos buzios',
 'santa maria da vitoria',
 'pedro leopoldo',
 'tres marias',
 'santo antonio de padua',
 'porto feliz',
 'gaspar',
 'palhoca',
 'pouso alegre',
 'guaiuba',
 'fraiburgo',
 'aurea',
 'botucatu',
 'corumba',
 'cajamar',
 'queimados',
 'sao jorge do ivai',
 'nova laranjeiras',
 'guaxupe',
 'osvaldo cruz',
 'ivora',
 'anaurilandia',
 'caraguatatuba',
 'regeneracao',
 'bilac',
 'faxinal',
 'pedro velho',
 'uberaba',
 'viamao',
 'cachoeira de minas',
 'coelho neto',
 'itajobi',
 'carmo do rio claro',
 'marica',
 'campo novo do parecis',
 'boa vista',
 'ipameri',
 'carlos barbosa',
 'anicuns',
 'rio bananal',
 'lavras da mangabeira',
 'balsamo',
 'guariba',
 'sao vendelino',
 'campo mourao',
 'aracati',
 'santo antonio do descoberto',
 'santo amaro da imperatriz',
 'betim',
 'vicosa',
 'dom eliseu',
 'campo largo',
 'santa rosa de lima',
 'quissama',
 'mirandopolis',
 'itapevi',
 'francisco beltrao',
 "dias d'avila",
 'novo horizonte',
 'poa',
 'querencia',
 'campo grande',
 'pedreira',
 'pariquera-acu',
 'itabaianinha',
 'pitangui',
 'araruama',
 'campo formoso',
 'guanambi',
 'itapolis',
 'pederneiras',
 'itabirito',
 'itaipava',
 'arroio do sal',
 'glaura',
 'lagoa vermelha',
 'mantena',
 'peruibe',
 'tubarao',
 'bonfim',
 'alvorada',
 'patrocinio',
 'mineiros',
 'itabuna',
 'tijucas',
 'santo antonio de jesus',
 'canarana',
 'itapecerica da serra',
 'nova prata do iguacu',
 'treze tilias',
 'anchieta',
 'quatigua',
 'iturama',
 'tres de maio',
 'santa rita do passa quatro',
 'porto esperidiao',
 'bonfim paulista',
 'cajuru',
 'cacador',
 'paragominas',
 'boa esperanca do sul',
 'tres pontas',
 'juazeiro do norte',
 'bambui',
 'comendador levy gasparian',
 'sao miguel do aleixo',
 'palmeira dos indios',
 'cerquilho',
 'saudade do iguacu',
 'ipaussu',
 'alto paraiso de goias',
 'santa isabel',
 'quirinopolis',
 'caruaru',
 'casimiro de abreu',
 'chavantes',
 'ecoporanga',
 'cachoeira paulista',
 'rio verde',
 'maracanau',
 'canoinhas',
 'ituverava',
 'buriti dos lopes',
 'rio do antonio',
 'guaranta',
 'santa luzia',
 'tucurui',
 'paranavai',
 'pinhais',
 'governador valadares',
 'trajano de moraes',
 'caete',
 'abaetetuba',
 'lavras',
 'coronel joao sa',
 'divino',
 'macaubas',
 'lucelia',
 'brejo da madre de deus',
 'carai',
 'corbelia',
 'varginha',
 'ouro preto',
 'prado',
 'colniza',
 'piuma',
 'rancharia',
 'barretos',
 'eunapolis',
 'floresta',
 'sao jose do norte',
 'rio bonito',
 'vargem bonita',
 'monte mor',
 'valente',
 'balsas',
 'nhandeara',
 'lauro de freitas',
 'osorio',
 'machado',
 'sao leopoldo',
 'soledade',
 'assis',
 'guarapari',
 'santo antonio do caiua',
 'esteio',
 'cambuci',
 'campina grande do sul',
 'baixo guandu',
 'fernao',
 'ibitinga',
 'santa cruz das palmeiras',
 'vila muriqui',
 'sao mateus',
 'piracuruca',
 'cordeiro',
 'cachoeira do sul',
 'barra do pirai',
 'castro',
 'ico',
 'sete lagoas',
 'itumbiara',
 'aluminio',
 'jatai',
 'frederico westphalen',
 'goioere',
 'sao jose da tapera',
 'porto uniao',
 'cocalinho',
 'curitibanos',
 'campos novos',
 'ubatuba',
 'monte santo de minas',
 'ribeirao das neves',
 'sao simao',
 'urutai',
 'itaobim',
 'liberdade',
 'arcos',
 'ribeirao',
 'patos de minas',
 'penapolis',
 'eusebio',
 'cordeiros',
 'victor graeff',
 'santa rita do araguaia',
 'poxoreu',
 'ananas',
 'conceicao dos ouros',
 'alagoinhas',
 'sao joao da barra',
 'lindoia',
 'bonfinopolis',
 'ibiam',
 'morungaba',
 'andradina',
 'tatui',
 'mata verde',
 'cornelio procopio',
 'itapipoca',
 'queluz',
 'godoy moreira',
 'iracemapolis',
 'buritizeiro',
 'xique-xique',
 'uruacu',
 'japi',
 'itauna',
 'sao francisco de assis',
 'pitangueiras',
 'ze doca',
 'dracena',
 'cachoeiras de macacu',
 'barauna',
 'formiga',
 'rodeio',
 'jequie',
 'juvenilia',
 'poco fundo',
 'amparo',
 'lauro muller',
 'japeri',
 'ourinhos',
 'lagoa dos gatos',
 'embu-guacu',
 'nossa senhora do remedio',
 'tambau',
 'orlandia',
 'bananeiras',
 'sao joao do manhuacu',
 'sarandi',
 'congonhas',
 'boa esperanca',
 'sandolandia',
 'garca',
 'descalvado',
 'guaracai',
 'aruana',
 'inga',
 'taio',
 'gaurama',
 'praia grande',
 'janauba',
 'nova monte verde',
 'mongagua',
 'monte alto',
 'sao joao do piaui',
 'primavera do leste',
 'seropedica',
 'indaial',
 'teofilo otoni',
 'santa terezinha',
 'planaltina',
 'caravelas',
 'muritiba',
 'itatiba',
 'piumhii',
 'pitanga',
 'capelinha',
 'ipero',
 'tarabai',
 'aparecida do taboado',
 'maioba',
 'monnerat',
 'sao lourenco do sul',
 'biguacu',
 'venda nova do imigrante',
 'arapoti',
 'fazenda rio grande',
 'senges',
 'aracruz',
 'canela',
 'porto franco',
 'veranopolis',
 'candiota',
 'carmo do paranaiba',
 'itacare',
 'desembargador otoni',
 'joanopolis',
 'registro',
 'ipiranga do norte',
 'felipe guerra',
 'dumont',
 'itapetininga',
 'bom despacho',
 'lagoa santa',
 'estacao',
 'panorama',
 'palmares',
 'prata',
 'santa adelia',
 'iguaba grande',
 'sarzedo',
 'dourado',
 'alcinopolis',
 'limoeiro do norte',
 'ibiraci',
 'ilhabela',
 'icara',
 'paiva',
 'batatais',
 'formoso do araguaia',
 'itapaci',
 'fernandopolis',
 'miguel pereira',
 'tocos',
 'campos do jordao',
 'catalao',
 'sao jose da lapa',
 'marituba',
 'arapora',
 'turvo',
 'rubiataba',
 'guaruja do sul',
 'pedra bela',
 'perdizes',
 'jesuania',
 'antonio carlos',
 'itapecerica',
 'monte belo',
 'mossoro',
 'piraju',
 'encruzilhada do sul',
 'igaratinga',
 'sao luis de montes belos',
 'santa rosa',
 'lagoinha',
 'redentora',
 'cuite',
 'coxim',
 'lucas do rio verde',
 'ibirataia',
 'olimpia',
 'cedro',
 'mario campos',
 'umuarama',
 'nova xavantina',
 'sao borja',
 'aguai',
 'itapira',
 'uniao da vitoria',
 'nova odessa',
 'itapuranga',
 'nova cruz',
 'apuiares',
 'almirante tamandare',
 'correia pinto',
 'itamarandiba',
 'juscimeira',
 'ipora',
 'cedro de sao joao',
 "santa barbara d'oeste",
 'sao joao da urtiga',
 'valparaiso de goias',
 'jussara',
 'capao da canoa',
 'araxa',
 'campo belo',
 'monte aprazivel',
 'bom jesus do querendo',
 'socorro',
 'catanduva',
 'monte castelo',
 'tabatinga',
 'bayeux',
 'ijui',
 'tangara da serra',
 'campos borges',
 'palma',
 'minacu',
 'miracema',
 'taruma',
 'sao francisco do sul',
 'cedral',
 'camaragibe',
 'lajeado',
 'cerqueira cesar',
 'frutal',
 'igarata',
 'novo gama',
 'sapucaia do sul',
 'juquitiba',
 'terra boa',
 'joao monlevade',
 'porangatu',
 'formosa da serra negra',
 'rafard',
 'rainha do mar',
 'pontal',
 'rio do sul',
 'nilopolis',
 'maracaju',
 'santo augusto',
 'banabuiu',
 'buenopolis',
 'barbalha',
 'quintana',
 'chorrocho',
 'votuporanga',
 'poco verde',
 'cipo-guacu',
 'santarem',
 'santa clara do sul',
 'ibiuna',
 'capivari',
 'arraias',
 'patos',
 'sao francisco do guapore',
 'vitoria da conquista',
 'urucuca',
 'vacaria',
 'campos altos',
 'nossa senhora do socorro',
 'cruzeiro do sul',
 'cataguases',
 'varzea grande',
 'santa rita do sapucai',
 'jaboticabal',
 'ilha comprida',
 'brasilia de minas',
 'moreno',
 'capanema',
 'tombos',
 'espumoso',
 'ouro branco',
 'valenca do piaui',
 'igrejinha',
 'engenheiro coelho',
 'parauapebas',
 'afonso claudio',
 'sao bernardo',
 'salto do jacui',
 'pires do rio',
 'astorga',
 'medina',
 'porto ferreira',
 'aracariguama',
 'hidrolandia',
 'virginopolis',
 'soledade de minas',
 'casca',
 'sapiranga',
 'angatuba',
 'ibirapua',
 'itupeva',
 'espera feliz',
 'penedo',
 'ibirite',
 'miracatu',
 'francisco santos',
 'paracambi',
 'cardoso',
 'floriano',
 'rondonopolis',
 'barra de sao francisco',
 'lavinia',
 'guajara-mirim',
 'guimaraes',
 'sao tome',
 'medianeira',
 'conceicao das pedras',
 'rinopolis',
 'capim grosso',
 'guaira',
 'euclides da cunha paulista',
 'lagoa da prata',
 'nanuque',
 'luis antonio',
 'senador firmino',
 'viradouro',
 'itabera',
 'cambara',
 'sananduva',
 'tapera',
 'tupaciguara',
 'colombo',
 'ananindeua',
 'coribe',
 'rio doce',
 'mogi mirim',
 'tocos do moji',
 'beberibe',
 'formosa do rio preto',
 'claudio',
 'rio paranaiba',
 'humberto de campos',
 'camocim de sao felix',
 'santo antonio de posse',
 'mesquita',
 'passa quatro',
 'belo oriente',
 'alto araguaia',
 'igarassu',
 'porto velho',
 'cajazeiras',
 'garopaba',
 'rio azul',
 'dois corregos',
 'sooretama',
 'cruzeiro do oeste',
 'nazare paulista',
 'riversul',
 'iguaracu',
 'maracas',
 'parana',
 'reboucas',
 'ametista do sul',
 'itu',
 'cacu',
 'vespasiano',
 'lindolfo collor',
 'sao lourenco',
 'santana do sobrado',
 'cafelandia',
 'ibiapina',
 'schroeder',
 'sao joao do oriente',
 'matao',
 'itanhandu',
 'santo angelo',
 'capinopolis',
 'colatina',
 'nova mutum',
 'munhoz de melo',
 'ibate',
 'unai',
 'medeiros neto',
 'anta',
 'ouroeste',
 'central',
 'nova independencia',
 'itapema',
 'sao jose do cedro',
 'camutanga',
 'ipumirim',
 'cristalia',
 'andira',
 'panelas',
 'comodoro',
 'domingos martins',
 'tangua',
 'sao gotardo',
 'araguaina',
 'ilheus',
 'louveira',
 'imbituba',
 'ouricuri',
 'itatinga',
 'santo cristo',
 "arraial d'ajuda",
 'piracanjuba',
 'russas',
 'lambari',
 'vargem alta',
 'sacra familia do tingua',
 'assis chateaubriand',
 'lago da pedra',
 'unistalda',
 'sao joao evangelista',
 'paramirim',
 'goias',
 'paracuru',
 'cruz alta',
 'presidente bernardes',
 'pains',
 'sao goncalo do rio preto',
 'jacinto machado',
 'sobralia',
 'maraba',
 'paraibuna',
 'toropi',
 'jauru',
 'cristalandia',
 'castelo do piaui',
 'ibipora',
 'presidente dutra',
 'vera cruz',
 'paulo frontin',
 ...]

In [58]:
# 피봇테이블 = 기존 데이터에서 추가적으로 필터링을 해서 값을 찾아오는 것

import pandas as pd
doc_covid = pd.read_csv("COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv", encoding="utf-8-sig")
doc_covid.head()

      FIPS     Admin2  ... Active                   Combined_Key
0  45001.0  Abbeville  ...      4  Abbeville, South Carolina, US
1  22001.0     Acadia  ...     46          Acadia, Louisiana, US
2  51001.0   Accomack  ...      7         Accomack, Virginia, US
3  16001.0        Ada  ...    192                 Ada, Idaho, US
4  19001.0      Adair  ...      1                Adair, Iowa, US

[5 rows x 12 columns]

In [59]:
import pandas as pd

doc_covid3 = pd.pivot_table(doc_covid, 
                index=["Country_Region"], 
                values=["Confirmed", "Deaths"], 
                aggfunc={"Confirmed": "sum", "Deaths": "mean"}, 
                fill_value=0,
                margins=True,
                margins_name="Total"
            ) 
# fill_value=0 : 결측치가 있다면 그 값을 0으로 만들어

doc_covid3.head()

                Confirmed  Deaths
Country_Region
Afghanistan           192     4.0
Albania               259    15.0
Algeria               847    58.0
Andorra               390    14.0
Angola                  8     2.0

In [61]:
doc_covid3[doc_covid3.index == "Total"]

                Confirmed     Deaths
Country_Region
Total              938959  20.477002

In [63]:
doc_covid3.style.format({
    "Confirmed": "{:,}",
    "Deaths": "{:..2f}"
})

ValueError: Format specifier missing precision